### ISSUE TITLE
There is a stored XSS vulnerability in the basic data-grade management function(基础资料-年级管理)

### ISSUE THREAD

**Issue by unafraid-fearless** [chenglun11/dormitory#2]
Test insert the following payload：
<img/src/onErroR=prompt`1`>
![image](https://github.com/chenglun11/DormitoryCMS/assets/36062846/07b4b823-68d9-41cf-9957-b80e269b0dc6)
Question interface：http://10.15.17.67:8888/dormitory/grade/create
![image](https://github.com/chenglun11/DormitoryCMS/assets/36062846/6b3a93dd-afd6-43be-88c7-f73ca3a208a3)
The results show
![image](https://github.com/chenglun11/DormitoryCMS/assets/36062846/767e7670-ccdb-4234-ad2c-c5d802e77688)

**Comment by chenglun11** [comment]
Thank you for your test, this xss vulnerability has been fixed
